version: '3.7'

services:
  app:
    build: .
    container_name: front
    restart: always
    ports:
      - '4000:4000'
    command: 'npm run start'
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 200M

  nginx:
    build: ./nginx
    container_name: front_nginx
    ports:
      - '80:80'
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
